# Generated by Django 5.0.6 on 2024-07-25 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=1000)),
                ('job_author', models.CharField(max_length=300, null=True)),
                ('bid', models.IntegerField(null=True)),
                ('cover_letter', models.TextField(max_length=1000)),
                ('applicant_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PostJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(max_length=1000)),
                ('budget', models.IntegerField()),
                ('tags', models.CharField(choices=[('html', 'HTML'), ('css', 'CSS'), ('python', 'Python')], default='Select Tags', max_length=50)),
                ('time_posted', models.DateTimeField(auto_now_add=True, null=True)),
                ('author', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('talent', 'Talent'), ('client', 'Client')], default='Who are you ?', max_length=30)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
